### PR TITLE
fix compatibility with BoringSSL

### PR DESCRIPTION
**Pull request by javierguerragiraldez**

### CODE REVIEW

**Review by fffonion — APPROVED** [review]

**Comment by fffonion** [comment]
wait for confirmation on this going into 3.1; i'm okay with the code change.

**Comment by gszr** [comment]
> wait for confirmation on this going into 3.1; i'm okay with the code change.

@fffonion has this been tested with a boringssl build?

**Comment by fffonion** [comment]
@gszr i have tested it locally with a boringssl build, it compiles, links and postgres SSL is working.

**Comment by gszr** [comment]
> @gszr i have tested it locally with a boringssl build, it compiles, links and postgres SSL is working.

Amazing news.

**Pull request merged**
